### PR TITLE
Access token

### LINKED ISSUE #24: Access code (BE)
As a user, when I want to create a new event, I first need to enter in an access code. If it's the correct code, I am redirected to the create from. If it's incorrect, I am notified the access code is incorrect. 

- [x] Create an authenticate method
- [ ] Run the authenticate method before creation 
- [ ] Require access token in create params

### PR DESCRIPTION
**Pull request by atkinson-daniel**
## What functionality does this accomplish?
**description**

Resolves #24 

1) Add access endpoint. Event creator will need to enter in an access code, currently '1234', in order to create an event.
2) Update seed files

### Test Coverage
- [x] No tests have been changed
- [ ] Some tests have been changed:
- [ ] All of the tests have been changed:
## Checklist:
- [x] I have reviewed my code
- [ ] I have annotated or commented my code, particularly in hard-to-understand areas
- [ ] I have fully tested my code
- [ ] I have partially tested my code (please explain why):

### CODE REVIEW

**Review by collinkallery — APPROVED** [review]
Thanks for this!

File: lib/drag_time_api_web/router.ex [hunk 1]
```diff
@@ -11,6 +11,7 @@ defmodule DragTimeApiWeb.Router do
     resources "/locations", LocationController, except: [:new, :edit]
     resources "/events", EventController, except: [:new, :edit]
     resources "/artists", ArtistController, except: [:new, :edit]
+    resources "/access", AccessController, execpt: [:new, :edit]
```
Comment (javier-aguilar) [inline lib/drag_time_api_web/router.ex:14]: You could probably do only: [:index] since that's the only we are using right now.

File: lib/drag_time_api_web/views/location_view.ex [hunk 2]
```diff
@@ -13,6 +13,9 @@ defmodule DragTimeApiWeb.LocationView do
   def render("location.json", %{location: location}) do
     %{id: location.id,
       name: location.name,
-      address: location.address}
+      address: location.address,
+      city: location.city,
+      state: location.state,
+      zip: location.zip}
   end
```
Comment (javier-aguilar) [inline lib/drag_time_api_web/views/location_view.ex:20]: Looks good! Can't believe we forgot to update this. lol

File: priv/repo/seeds.exs [hunk 3]
```diff
@@ -20,6 +20,30 @@ Repo.insert! %Location{
...
+Repo.insert! %Location{
+ name: "Hamburger Mary's Denver",
+ address: "1336 E 17th Ave",
+ city: "Denver",
+ state: "CO",
+ zip: "80218"
+}
+
+Repo.insert! %Location{
+ name: "Cheer Up Charlies",
```
Comment (javier-aguilar) [inline priv/repo/seeds.exs:40]: Didn't expect to see this here. Love that place. One of the things I miss about Austin <3

File: lib/drag_time_api_web/router.ex (hunk 1 above)
Comment (TravisBorgsmiller) [reply lib/drag_time_api_web/router.ex:14]: That is a good point, I don't think we will ever need the edit route

File: priv/repo/seeds.exs [hunk 4]
```diff
@@ -35,19 +59,79 @@ Repo.insert! %Event{
...
+
 alias DragTimeApi.Repo
 alias DragTimeApi.Artists.Artist
 
 Repo.insert! %Artist{
  name: "Landon Cider",
- image: "https://www.example.com/1.jpg",
- description: "lazy dog jumped over the fence"
+ image: "https://media.altpress.com/uploads/2019/10/2PhotobyBrettSaariHospitalHorrorEpisode-copy.jpg",
+ description: "‘DRAGULA’ SEASON 3 WINNER"
```
Comment (javier-aguilar) [inline priv/repo/seeds.exs:116]: This is better info to include!

**Review by javier-aguilar — APPROVED** [review]
